stages:
  - deploy

deploy:
  stage: deploy
  tags:
  - shellgcp-hu20 # gitlabrunner-tag


  only:
  - master #branch name that you want to deploy
  script:
  - echo $CI_PROJECT_DIR
  - cd
  - cd /home/gitlab-runner
  - gcloud auth activate-service-account --key-file shell2.json #getting authenticate with gcp service account key
  - gcloud config set project us-gcp-ame-con-116-npd-1
  - cd
  - cd $CI_PROJECT_DIR
  - gcloud builds submit . --config=cloudbuild.yaml --substitutions=TAG_NAME=${TAG}
